### ISSUE TITLE
Problems using install.sh

### ISSUE THREAD

**Issue by liamtoney** [kallstadt-usgs/seisk#16]
`install.sh` looks for `environment_osx.yml`, which doesn't exist. Running
```
$ ./install.sh -r
```
uses the `environment.yml` file, but conflicts are found and it's slow to solve. I removed the `ipython` and `python` version restrictions in `environment.yml` and then bypassed `install.sh` by running
```
$ conda env create
$ conda activate seisk
$ pip install -e .
```
in the head of the repo. Things are (tentatively) working. Not sure if removing those version restrictions will cause problems, but at least interactive plotting is working with the `Qt5Agg` backend after calling e.g.
```
$ ipython
In [1]: import matplotlib.pyplot as plt
In [2]: plt.scatter(47, 47)
```
with no optional flags.

If there end up being no issues with the less-restricted `environment.yml`, I'd suggest making those changes since conda is a whole lot happier...

**Comment by liamtoney** [comment]
I placed a `matplotlibrc` file in the top-level of the repo with the single line
```
backend : Qt5Agg
```
to specify the `Qt5Agg` backend.

**Comment by liamtoney** [comment]
I additionally constrained `obspy==1.1.1` in `environment.yml` to address [this ObsPy issue](https://github.com/obspy/obspy/issues/2434#issuecomment-518732770).

**Comment by liamtoney** [comment]
```yaml
name: seisk
channels:
- conda-forge
- defaults
dependencies:
- ipython
- basemap
- matplotlib
- numpy
- obspy==1.1.1
- pandas
- pytables
- pytest
- pytest-cov
- pytest-mpl
- python
- scipy
- scikit-learn
- scikit-image
- nitime
- moviepy
- jupyter
- pyqt
- mtspec
- statsmodels
- spyder
- xlrd
```
